version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ku_dream_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ku_dream_server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
