name: KUSD-server
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/KUSD_SERVER
            kill -9 $(lsof -t -i :8080)
            git add .
            git commit -m "temp commit"
            git fetch origin master
            git merge origin/master
            
            ./gradlew clean build
            source load-env.sh
            cd build
            cd libs
            nohup java -jar KUmap-0.0.1-SNAPSHOT.jar > application.log 2>&1 &
