name: KUSD-server
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: Rocky Linux 8.6
    steps:
      - name: Deploy spring MainServer(main)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd ~/kusd
            git add .
            git commit -m "temp commit"
            git fetch origin master
            git merge origin/master
            
            ./gradlew clean build
